---
apiVersion: v1
kind: ConfigMap
metadata:
  name: npm-registry
  namespace: npm-registry
  labels:
    app: npm-registry
data:
  config.yaml: |
    # links for configuration
    # https://github.com/verdaccio/verdaccio-cookbook
    # https://github.com/verdaccio/verdaccio/blob/master/conf/
    storage: /verdaccio/storage/data
    auth:
      htpasswd:
        file: /verdaccio/storage/htpasswd
        max_users: -1
    uplinks:
      npmjs:
        url: https://registry.npmjs.org/
    packages:
      '@*/*':
        access: $all
        publish: $authenticated
        proxy: npmjs
      '**':
        access: $all
        publish: $authenticated
        proxy: npmjs
    logs:
      - type: stdout
        format: pretty
        level: http